services:
  - type: web
    name: college-notes
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false        # <- You will paste your Neon URL in Render dashboard manually
      - key: CLOUDINARY_CLOUD_NAME
        value: dldydrqdb
      - key: CLOUDINARY_API_KEY
        value: 756177661263517
      - key: CLOUDINARY_API_SECRET
        value: PcA6CTww57imc8HAWi2tsN033eo
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false        # <- Paste the JSON content of your Firebase service account key here
